management:
  endpoints:
      web:
        exposure:
         include:
           '*'
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Singapore
    #url: jdbc:mysql://127.0.0.1:3306/Employee?serverTimezone=Asia/Singapore&createDatabaseIfNotExist=true  ---->This will create new DB every time start server if not exist
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop  --This will create table when start and drop the tables when stop
    
    
          
      
      
  