server:
  port: 8191
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sivasuit/spring-cloud-config-store
          search-paths:
          - '/rent-cloud-config/*service'